repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: name-tests-test
        args: ["--pytest-test-first"]
    -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: true
        types: [python]
        verbose: true
        stages: [commit]
        args: ["-v", "--cov=src", "--cov-report=term-missing", "--cov-report=html", "--testmon"]
