[pytest]
pythonpath = src
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts = -v
markers =
    asyncio: marks a test as an asyncio coroutine
    integration: marks a test as an integration test (deselect with '-m "not integration"')
env =
    DYNACONF_ENV=dev
asyncio_mode = auto
filterwarnings =
    ignore::telegram.warnings.PTBUserWarning
