[pytest]
pythonpath = src
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts = -v
markers =
    asyncio: mark a test as an asyncio coroutine
env =
    DYNACONF_ENV=dev
