default:
  # Dev mode
  DEBUG: false
  # Chat/bot data
  BOT_USERNAME:
  TOKEN:
  CHAT_ID:
  FORUM: false
  CHANNEL_USERNAME:
  ADMINS: []
  # Pathes
  DB_PATH: data/db
  LOG_PATH: logs/bot.log
  # General
  TIMEZONE: US/Eastern
  # Behavior
  WAR_MODE: true
  # Internal parameters
  DATETIME_FORMAT: '%Y-%m-%d %H:%M:%S'
  # Local parameters
  MAIN_THREAD_ID:
  WELCOME_THREAD_ID:
  OFFTOP_THREAD_ID:
  CHANNEL_THREAD_ID:

production:
  DEBUG: false
  BOT_USERNAME: '@PLACEHOLDER'
  TOKEN: SECRET_PLACEHOLDER
  CHAT_ID: PLACEHOLDER
  FORUM: true
  CHANNEL_USERNAME: '@PLACEHOLDER'
  ADMINS:
    - '@PLACEHOLDER'
  MAIN_THREAD_ID:    PLACEHOLDER
  WELCOME_THREAD_ID: PLACEHOLDER
  OFFTOP_THREAD_ID:  PLACEHOLDER
  CHANNEL_THREAD_ID: PLACEHOLDER

development:
  DEBUG: true
  BOT_USERNAME: '@PLACEHOLDER'
  TOKEN: SECRET_PLACEHOLDER
  CHAT_ID: PLACEHOLDER
  FORUM: false
  CHANNEL_USERNAME: '@PLACEHOLDER'
  ADMINS:
    - '@PLACEHOLDER'