[default]
# Pathes
db_path = 'data/db'
log_path = 'logs/bot.log'
# General
timezone = 'US/Eastern'
# Behavior
war_mode = true
war_start_date = '2022-02-24'
morning_time = '09:00:00'
# Internal parameters
date_format = '%Y-%m-%d'
datetime_format = '%Y-%m-%d %H:%M:%S'
welcome_timeout = 86400  # 1 day (in seconds)
cleanup_period = 129600  # 1.5 days (in seconds)

[prod]
debug = false
forum = true
bot_username = '@PLACEHOLDER'
chat_id = 'PLACEHOLDER'
chat_link_id = 'PLACEHOLDER'
chat_invite_link = 'PLACEHOLDER'
channel_username = '@PLACEHOLDER'
admins = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'

[prod.TOPICS]
[prod.TAGS]
[prod.PRIORITY]

[dev]
debug = true
forum = false
morning_time_offset = 10  # in seconds
welcome_timeout = 10  # in seconds
cleanup_period = 20   # in seconds
bot_username = '@PLACEHOLDER'
chat_id = 'PLACEHOLDER'
chat_link_id = 'PLACEHOLDER'
chat_invite_link = 'PLACEHOLDER'
channel_username = '@PLACEHOLDER'
admins = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'