[default]
# Pathes
db_path = 'data/db'
log_path = 'logs/bot.log'
# General
timezone = 'US/Eastern'
# Behavior
war_mode = true
war_start_date = '2022-02-24'
morning_time = '09:00:00'
agenda_mode = true
agenda_time = '07:00:00'
# Internal parameters
date_format = '%Y-%m-%d'
datetime_format = '%Y-%m-%d %H:%M:%S'
conversation_timeout = 900  # 15 minutes (in seconds)
welcome_timeout = 86400     # 1 day (in seconds)
cleanup_period = 129600     # 1.5 days (in seconds)

admins = ['@PLACEHOLDER']
default_agenda_image = 'PLACEHOLDER'

[default.TOPICS]
welcome = 0
[default.TAGS]
[default.PRIORITIES]

[prod]
debug = false
forum = true

chat_id = 'PLACEHOLDER'
chat_link_id = 'PLACEHOLDER'
chat_invite_link = 'PLACEHOLDER'
channel_username = '@PLACEHOLDER'
moderators = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'

[dev]
debug = true
forum = false
time_offset = 10            # in seconds
conversation_timeout = 30   # in seconds
welcome_timeout = 10        # in seconds
cleanup_period = 20         # in seconds

chat_id = 'PLACEHOLDER'
chat_link_id = 'PLACEHOLDER'
chat_invite_link = 'PLACEHOLDER'
channel_username = '@PLACEHOLDER'
moderators = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'
